[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "Iosevka NFP"
style = "Bold"

[font.bold_italic]
family = "Iosevka NFP"
style = "Bold Italic"

[font.italic]
family = "Iosevka NFP"
style = "Italic"

[font.normal]
family = "Iosevka NFP"
style = "Regular"

[window]
opacity = 1.0
startup_mode = "Maximized"
title = "Terminal"
option_as_alt = "Both"

[window.padding]
x = 5
y = 5

# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux"]
